function [sachead,data]=read_sac_bin(fname)
	fid=fopen(fname,'rb');
	if fid==-1
		fprintf(strcat('Error opening file',fname));
		return;
	end
%---------------read 70  float ------------------
	[tt,count]=fread(fid,70,'float32');
	sachead.delta=tt(1)	;		% RF time increment, sec    %
	sachead.depmin=tt(2);			%    minimum amplitude      %
	sachead.depmax=tt(3);			%    maximum amplitude      %
	sachead.scale=tt(4);			%    amplitude scale factor %
	sachead.odelta=tt(5);				%    observed time inc      %
	sachead.b=tt(6);				% RD initial time - wrt nz* %
	sachead.e=tt(7);				% RD end time               %
	sachead.o=tt(8);				%    event start            %
	sachead.a=tt(9);				%    1st arrival time       %
	sachead.internal1=tt(10);			%    internal use           %
	sachead.t0=tt(11);				%    user-defined time pick %
	sachead.t1=tt(12);				%    user-defined time pick %
	sachead.t2=tt(13);				%    user-defined time pick %
	sachead.t3=tt(14);			%    user-defined time pick %
	sachead.t4=tt(15);				%    user-defined time pick %
	sachead.t5=tt(16);				%    user-defined time pick %
	sachead.t6=tt(17);				%    user-defined time pick %
	sachead.t7=tt(18);				%    user-defined time pick %
	sachead.t8=tt(19);				%    user-defined time pick %
	sachead.t9=tt(20);				%    user-defined time pick %
	sachead.f=tt(21);				%    event end, sec > 0     %
	sachead.resp0=tt(22);				%    instrument respnse parm%
	sachead.resp1=tt(23);				%    instrument respnse parm%
	sachead.resp2=tt(24);				%    instrument respnse parm%
	sachead.resp3=tt(25);				%    instrument respnse parm%
	sachead.resp4=tt(26);				%    instrument respnse parm%
	sachead.resp5=tt(27);				%    instrument respnse parm%
	sachead.resp6=tt(28);				%    instrument respnse parm%
	sachead.resp7=tt(29);				%    instrument respnse parm%
	sachead.resp8=tt(30);				%    instrument respnse parm%
	sachead.resp9=tt(31);				%    instrument respnse parm%
	sachead.stla=tt(32)	;			%  T station latititude     %
	sachead.stlo=tt(33)	;			%  T station longitude      %
	sachead.stel=tt(34)	;			%  T station elevation, m   %
	sachead.stdp=tt(35)	;			%  T station depth, m      %
	sachead.evla=tt(36)	;			%    event latitude         %
	sachead.evlo=tt(37)	;			%    event longitude        %
	sachead.evel=tt(38)	;			%    event elevation        %
	sachead.evdp=tt(39)	;			%    event depth            %
	sachead.mag=tt(40)	;	        %    reserved for future use%
	sachead.user0=tt(41);				%    available to user      %
	sachead.user1=tt(42);				%    available to user      %
	sachead.user2=tt(43);			%    available to user      %
	sachead.user3=tt(44);			%    available to user      %
	sachead.user4=tt(45);			%    available to user      %
	sachead.user5=tt(46);			%    available to user      %
	sachead.user6=tt(47);			%    available to user      %
	sachead.user7=tt(48);			%    available to user      %
	sachead.user8=tt(49);			%    available to user      %
	sachead.user9=tt(50);			%    available to user      %
	sachead.dist=tt(51)	;		%    stn-event distance, km %
	sachead.az=tt(52)	;		%    event-stn azimuth      %
	sachead.baz=tt(53)	;		%    stn-event azimuth      %
	sachead.gcarc=tt(54);			%    stn-event dist, degrees%
	sachead.internal2=tt(55);		%    internal use           %
	sachead.internal3=tt(56);		%    internal use           %
	sachead.depmen=tt(57)	;		%    mean value, amplitude  %
	sachead.cmpaz=tt(58)	;		%  T component azimuth     %
	sachead.cmpinc=tt(59)	;		%  T component inclination %
	sachead.xminimum=tt(60)	;	%   Minimum value of X (Spectral files only)	%
	sachead.xmaximum=tt(61)	;	%    Maximum value of X (Spectral files only)	%
	sachead.yminimum=tt(62)	;	%    Minimum value of Y (Spectral files only)	%
	sachead.ymaximum=tt(63)	;	%    Maximum value of Y (Spectral files only)	%
	sachead.unused6=tt(64)	;	%    reserved for future use%
	sachead.unused7=tt(65)	;	%    reserved for future use%
	sachead.unused8=tt(66)	;	%    reserved for future use%
	sachead.unused9=tt(67)	;	%    reserved for future use%
	sachead.unused10=tt(68)	;	%    reserved for future use%
	sachead.unused11=tt(69)	;	%    reserved for future use%
% -----read 40 integers -----------------	
	[tt,count]=fread(fid,40,'int32');
 
	sachead.nzyear=tt(1);
	sachead.nzjday=tt(2);
	sachead.nzhour=tt(3);
	sachead.nzmin=tt(4);
	sachead.nzsec=tt(5);
	sachead.nzmsec=tt(6);
	sachead.nvhdr=tt(7);
	sachead.norid=tt(8);
	sachead.nevid=tt(9);
	sachead.npts=tt(10);
	sachead.internal7=tt(11);
	sachead.nwfid=tt(12);
	sachead.nxsize=tt(13);
	sachead.nysize=tt(14);
	sachead.unused15=tt(15);
	sachead.iftype=tt(16);
	sachead.idep=tt(17);
	sachead.iztype=tt(18);
	sachead.unused16=tt(19);
	sachead.iinst=tt(20);
	sachead.istreg=tt(21);
	sachead.ievreg=tt(22);
	sachead.ievtyp=tt(23);
	sachead.iqual=tt(24);
	sachead.isynth=tt(25);
	sachead.imagtyp=tt(26);
	sachead.imagsrc=tt(27);
	sachead.unused19=tt(28);
	sachead.unused20=tt(29);
	sachead.unused21=tt(30);
	sachead.unused22=tt(31);
	sachead.unused23=tt(32);
	sachead.unused24=tt(33);
	sachead.unused25=tt(34);
	sachead.unused26=tt(35);
	sachead.leven=tt(36);
	sachead.lpspol=tt(37);
	sachead.lovrok=tt(38);
	sachead.lcalda=tt(39);
	sachead.unused27=tt(40);
% -----------read 192 character -------------	
	[xx,count]=fread(fid,192,'*char');
	sachead.kstnm=xx(1:8);		%  F station name           %
	sachead.kevnm=xx(9:24);		%    event name             %
	sachead.khole=xx(25:32);		%    man-made event name    %
	sachead.ko=xx(33:40)	;		%    event origin time id   %
	sachead.ka=xx(41:48)	;		%    1st arrival time ident %
	sachead.kt0=xx(49:56)	;		%    time pick 0 ident      %
	sachead.kt1=xx(57:64)	;		%    time pick 1 ident      %
	sachead.kt2=xx(65:72)	;		%    time pick 2 ident      %
	sachead.kt3=xx(73:80)	;		%    time pick 3 ident      %
	sachead.kt4=xx(81:88)	;		%    time pick 4 ident      %
	sachead.kt5=xx(89:96)	;	%    time pick 5 ident      %
	sachead.kt6=xx(97:104)	;	%    time pick 6 ident      %
	sachead.kt7=xx(105:112)	;		%    time pick 7 ident      %
	sachead.kt8=xx(113:120)	;		%    time pick 8 ident      %
	sachead.kt9=xx(121:128)	;		%    time pick 9 ident      %
	sachead.kf=xx(129:136)	;		%    end of event ident     %
	sachead.kuser0=xx(137:144);		%    available to user      %
	sachead.kuser1=xx(145:152);		%    available to user      %
	sachead.kuser2=xx(153:160);		%    available to user      %
	sachead.kcmpnm=xx(161:168);		%  F component name         %
	sachead.knetwk=xx(169:176);		%    network name           %
	sachead.kdatrd=xx(177:184);		%    date data read         %
	sachead.kinst=xx(185:192)	;	%    instrument name        %	

% ----read data-------------------
	[data,count]=fread(fid,sachead.npts,'float32');

end
